### ISSUE TITLE
Implement focus as a getDisplayMedia parameter instead

### ISSUE THREAD

**Issue by antosart** [WICG/conditional-focus#1]
In order to address the clickjacking concerns, wouldn't it be possible instead to implement this by passing a function to getDisplayMedia? Example code:

```javascript
const stream = await navigator.mediaDevices.getDisplayMedia({focus: ShouldFocus});

function ShouldFocus(stream) {
  const [track] = stream.getVideoTracks();
  if (sampleUsesCaptureHandle) {
    // Assume logic discriminating focusability by origin,
    // for instance focusing anything except https://collaborator.com.
    const captureHandle = track.getCaptureHandle();
    return ShouldFocusOrigin(captureHandle && captureHandle.origin);
  } else {  // Assume Capture Handle is not a thing.
    // Assume the application is only interested in focusing tabs, not windows.
    return track.getSettings().displaySurface == 'browser';
  }
}
```

**Comment by eladalon1983** [comment]
When will this function be called?
* If before the `Promise` is resolved, then this gives the app access to the stream before the `Promise` gets resolved - a messy issue.
* If after, then it happens later than with the current proposal - a drawback.

**Comment by antosart** [comment]
After. From the sample code in your explainer, you also propose to call `.focus()` after `navigator.mediaDevices.getDisplayMedia()` resolves, so I don't see any difference.

**Comment by eladalon1983** [comment]
> so I don't see any difference

When calling after, the question arises - **how long after?**
Call the microtask on which the `Promise` gets resolved "`MT`".
The callback approach leads to the focus window-of-opportunity being left open for long. Let's only look at the case when the application makes an explicit decision.
* My suggested approach: the focus-decision is made while `MT` is still executing.
* Callback approach: the focus-decision is made on an **additional microtask** which is scheduled to run **after** `MT` finishes executing.

**Comment by antosart** [comment]
Ok, now I understand your previous [comment](https://github.com/WICG/conditional-focus/issues/1#issuecomment-925685435) and it makes sense to me. Closing this.
